namespace QuantityTakeoffService.MassTransitContracts;

/// <summary>
/// Message contract indicating successful completion of a Trimble BIM model processing operation.
/// Contains all necessary information about the processed model, its output file location, and
/// metadata needed for notifications and further processing. This contract is published by the
/// model conversion processor and consumed by the model conversion state machine to track
/// the processing workflow.
/// </summary>
public interface ITrimBimModelProcessingCompleted
{
    /// <summary>
    /// The job identifier that this model belongs to
    /// </summary>
    string JobId { get; set; }

    /// <summary>
    /// The unique identifier of the model entry in JobModelMetaData collection
    /// </summary>
    string JobModelId { get; set; }

    /// <summary>
    /// The identifier of the model in Trimble Connect
    /// </summary>
    string TrimbleConnectModelId { get; set; }

    /// <summary>
    /// Unique identifier used to correlate this processing request with its corresponding 
    /// completion or failure messages across distributed services, enabling end-to-end
    /// traceability of the asynchronous processing workflow.
    /// </summary>
    /// <remarks>
    /// The CorrelationId is generated when publishing a model processing message and is passed 
    /// to the orchestration service, which then includes it in any completion or failure messages.
    /// This enables proper message routing and provides a consistent identifier for logging, 
    /// troubleshooting and monitoring the asynchronous processing workflow.
    /// </remarks>
    public Guid CorrelationId { get; }

    /// <summary>
    /// The identifier of the customer who owns this model
    /// </summary>
    public string CustomerId { get; }

    /// <summary>
    /// The identifier of the converted model file in the Trimble File Service.
    /// This ID is generated when the processed model JSON is uploaded to the file service
    /// and is used for subsequent file retrieval and reference in metadata collections.
    /// </summary>
    public string TFSFileId { get; set; }

    /// <summary>
    /// The temporary URL that provides direct download access to the processed model file.
    /// This URL is generated by the Trimble File Service and is used by clients to retrieve
    /// the model without requiring additional authorization steps.
    /// </summary>
    public string ModelFileDownloadUrl { get; set; }

    /// <summary>
    /// The UTC timestamp when the model processing operation was completed.
    /// </summary>
    DateTime ProcessingCompletedOnUtc { get; set; }

    /// <summary>
    /// The identifier of the notification group that should receive updates about this
    /// model's processing status
    /// </summary>
    string NotificationGroupId { get; set; }
}
